Typos in chapters 8 and 9
cs3110/textbook pull request #43
Opened 2022-01-27 15:16 UTC by vitalydolgov

I've gathered some typos I found while I was doing the course. I feel a bit anxious because I'm certainly not an expert in the topic... But anyway, I hope at least something is of benefit :)

2022-01-27 18:25 UTC, jnfoster commented on src/chapters/ds/hash_tables.md
> +    (* insert (k, v) into [tab] *)
Shouldn't the pair also be in brackets?

2022-01-27 18:28 UTC, jnfoster requested changes
Looks good, but can you address the two minor comments?

2022-01-27 18:28 UTC, jnfoster commented on src/chapters/ds/memoization.md
> +  let h = Hashtbl.create 16 in
Why?

2022-01-28 14:07 UTC, vitalydolgov commented on src/chapters/ds/memoization.md
> +  let h = Hashtbl.create 16 in
I changed the initial size for it to be consistent with other examples from "Hash Tables" chapter, and even in this chapter just the next snippet defines a table of size 16. Also, IIRC prof. Clarkson mentioned somewhere in the videos, that a power of 2 is the optimal size for performance of a hash table as it doubles and halves all the time, but I can be wrong.

2022-01-28 14:11 UTC, vitalydolgov commented on src/chapters/ds/hash_tables.md
> +    (* insert (k, v) into [tab] *)
I agree, standard library also emphasizes such things.

2022-01-30 13:13 UTC, jnfoster commented on src/chapters/ds/memoization.md
> +  let h = Hashtbl.create 16 in
I haven't watched all the videos. But, depending on the hash function being used, having the capacity of the underlying structure be a power of 2 can be *anti*-optimal. So often a prime number is used as the initial value instead. @clarksmr can you recall what you said in the videos?

2022-01-30 14:06 UTC, clarksmr commented on src/chapters/ds/memoization.md
> +  let h = Hashtbl.create 16 in
If I did say something like that, it was most certainly an error.  I wonder if OP is thinking about the amortized analysis:  I use power-of-two sizes there to make the analysis easier.  Or maybe I pointed out that the default minimum number of buckets in `Hashtbl` [is 16](https://github.com/ocaml/ocaml/blob/53d5d05daa1f3046344a54c9d656402a00736872/stdlib/hashtbl.ml#L74).

2022-01-30 14:07 UTC, jnfoster commented on src/chapters/ds/memoization.md
> +  let h = Hashtbl.create 16 in
Thanks. And sorry to bother you on a Sunday morning!

2022-01-30 18:05 UTC, vitalydolgov commented on src/chapters/ds/memoization.md
> +  let h = Hashtbl.create 16 in
I'm sorry I was wrong :( @clarksmr certainly didn't say that in videos, the thing I was referenced to is [this phrase](https://github.com/cs3110/textbook/blob/7b22e76b32c244583a58d27ee8431669dbad8974/src/chapters/ds/hash_tables.md?plain=1#L694) regarding efficiency of a hash function, which I interpreted incorrectly.

>  So often a prime number is used as the initial value instead.

To me it's not obvious at all, could you please consider adding such important knowledge to lectures?

I will change this "fix" back, let me know if you want to update other `Hashtbl.create`. Thank you for your patience.

2022-05-31 14:10 UTC, vitalydolgov commented
Hi there! Are changes in this PR still valid and waiting for something to happen before merge, or should I just close it?

2022-05-31 14:25 UTC, merged